In [160]:
import pandas as pd
import matplotlib.pyplot as plt
import warnings
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


# Suppress all warnings
warnings.filterwarnings("ignore")

In [199]:
train = pd.read_csv('./DataSets/titanic/train.csv')
test = pd.read_csv('./DataSets/titanic/test.csv')

In [200]:
train.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S  
9      0            237736  30.0708   NaN        C

In [220]:
print(train.shape)

(891, 12)


In [217]:
train_X=train.drop(['PassengerId','Name', 'SibSp',
       'Parch','Survived', 'Ticket'],axis=1)
train_X = train_X.fillna('0')
print(train_X)
print(train_X.size)

     Pclass     Sex   Age     Fare Cabin Embarked
0         3    male  22.0   7.2500     0        S
1         1  female  38.0  71.2833   C85        C
2         3  female  26.0   7.9250     0        S
3         1  female  35.0  53.1000  C123        S
4         3    male  35.0   8.0500     0        S
..      ...     ...   ...      ...   ...      ...
886       2    male  27.0  13.0000     0        S
887       1  female  19.0  30.0000   B42        S
888       3  female     0  23.4500     0        S
889       1    male  26.0  30.0000  C148        C
890       3    male  32.0   7.7500     0        Q

[891 rows x 6 columns]
5346


In [221]:
train_y=train['Survived']
print(train_y.shape)

(891,)


In [204]:
categorical_features = ['Pclass','Sex', 'Embarked','Cabin']

preprocessor = ColumnTransformer(
    transformers=[
        ('cat', OneHotEncoder(handle_unknown='ignore',sparse_output=False), categorical_features)
    ],
    remainder='passthrough'
)
preprocessor.fit_transform(train_X)

array([[0.0, 0.0, 1.0, ..., 0.0, 22.0, 7.25],
       [1.0, 0.0, 0.0, ..., 0.0, 38.0, 71.2833],
       [0.0, 0.0, 1.0, ..., 0.0, 26.0, 7.925],
       ...,
       [0.0, 0.0, 1.0, ..., 0.0, '0', 23.45],
       [1.0, 0.0, 0.0, ..., 0.0, 26.0, 30.0],
       [0.0, 0.0, 1.0, ..., 0.0, 32.0, 7.75]], dtype=object)

In [205]:
train_X=preprocessor.transform(train_X)

In [206]:
print(train_X)

[[0.0 0.0 1.0 ... 0.0 22.0 7.25]
 [1.0 0.0 0.0 ... 0.0 38.0 71.2833]
 [0.0 0.0 1.0 ... 0.0 26.0 7.925]
 ...
 [0.0 0.0 1.0 ... 0.0 '0' 23.45]
 [1.0 0.0 0.0 ... 0.0 26.0 30.0]
 [0.0 0.0 1.0 ... 0.0 32.0 7.75]]


In [207]:
model=LinearRegression()
model.fit(X=train_X,y=train_y)

LinearRegression()

In [208]:
LogisModel=LogisticRegression()
LogisModel.fit(X=train_X,y=train_y)

LogisticRegression()

In [ ]:
print(model.predict(train_X))

[ 6.51321411e-02  9.99599457e-01  5.39394379e-01  7.41958618e-01
  4.06761169e-02  1.69998169e-01 -1.21688843e-03  1.11026764e-01
  5.39241791e-01  8.44272614e-01  5.22235870e-01  9.99038696e-01
  6.94007874e-02  4.57763672e-02  5.62335968e-01  6.71073914e-01
  1.77520752e-01  2.93197632e-01  5.35354614e-01  6.75758362e-01
  2.33314514e-01  9.98916626e-01  6.22589111e-01  1.00163651e+00
  5.81089020e-01  5.29304504e-01  1.94206238e-01  2.82497406e-01
  6.51233673e-01  1.07616425e-01  3.13156128e-01  1.00243378e+00
  6.51161194e-01  1.65435791e-01  3.66046906e-01  2.35702515e-01
  1.94210052e-01  6.74858093e-02  5.60249329e-01  6.51157379e-01
  5.13435364e-01  7.27439880e-01  1.94576263e-01  8.71658325e-01
  6.14849091e-01  1.07700348e-01  1.73866272e-01  6.51161194e-01
  2.02148438e-01  5.60138702e-01  1.11675262e-01  6.73484802e-02
  1.23883057e+00  7.26356506e-01 -7.09533691e-04  1.03063965e+00
  7.33161926e-01  1.39633179e-01  7.73277283e-01  1.07978821e-01
  1.52080536e-01  1.02734

In [192]:
test_X=test.drop(['PassengerId','Name', 'SibSp',
       'Parch', 'Ticket'],axis=1)
test_X=test_X.fillna('0')
test_X['Cabin'].isna().sum()

np.int64(0)

In [189]:
test_X['Cabin'].isna().sum()

np.int64(327)

In [193]:
test_X=preprocessor.transform(test_X)
print(test_X)

[[0.0 0.0 1.0 ... 0.0 34.5 7.8292]
 [0.0 0.0 1.0 ... 0.0 47.0 7.0]
 [0.0 1.0 0.0 ... 0.0 62.0 9.6875]
 ...
 [0.0 0.0 1.0 ... 0.0 38.5 7.25]
 [0.0 0.0 1.0 ... 0.0 '0' 8.05]
 [0.0 0.0 1.0 ... 0.0 '0' 22.3583]]


In [198]:
# test_y=test['Survived']
# print(test_y)
print(test)

     PassengerId  Pclass                                          Name  \
0            892       3                              Kelly, Mr. James   
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
2            894       2                     Myles, Mr. Thomas Francis   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
..           ...     ...                                           ...   
413         1305       3                            Spector, Mr. Woolf   
414         1306       1                  Oliva y Ocana, Dona. Fermina   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   
417         1309       3                      Peter, Master. Michael J   

        Sex   Age  SibSp  Parch              Ticket      Fare Cabin Embarked  
0      male  34.5      0      0 

In [209]:
result=LogisModel.predict(train_X)

In [210]:
print(result)

[0 1 1 1 0 0 0 0 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 1 1 0 0 0 1 0 0 1 1 0 0 0 0
 0 1 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 0 1 1 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 0 0
 0 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 1 0 0 1 0
 1 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1 1 1 0 0 0 0 1
 1 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 1 0 0 1 1
 0 1 0 0 0 1 0 1 1 1 1 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0 1 0 0 0
 0 0 1 0 0 0 0 1 1 0 0 1 0 1 0 1 0 0 1 1 0 0 0 0 1 1 1 0 0 1 0 0 0 1 1 1 1
 1 0 0 0 0 1 0 0 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 1 1 1 1 0 0 1 0 0 1 1 0 1 1 1 1 0 0 1 1 0 1 1 0 0 1 1 0 1 0 1 0 1 1 0 0
 0 1 0 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 1 0 0 0 1 1 1 1
 1 0 0 0 1 1 1 1 0 0 1 1 0 1 0 0 0 1 0 1 1 0 0 1 1 0 0 0 0 1 0 0 1 0 1 0 0
 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 0 1 0 0 1 1 0 0 1 1 1 0 0 1 1 1 0 0 1 0 0 1
 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0
 0 0 0 1 1 1 0 0 0 0 0 0 

In [ ]:
print(train_X.shape)
print(train_y.shape)

# plt.scatter(train_X[:, 1], train_y, c=result)


(891, 6)
(891,)


InvalidIndexError: (slice(None, None, None), 1)

In [222]:
print(train_X.shape)
print(train_y.shape)

(891, 6)
(891,)
